### ISSUE TITLE
skill

### ISSUE THREAD

**Issue by PashaYakubovsky** [Mishatopkek/react-mini-apps#1]
kek

**Comment by PashaYakubovsky** [comment]
![mjg0thak40qd1](https://github.com/user-attachments/assets/065d13df-ca58-4949-829c-710165adbba1)

**Comment by Mishatopkek** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
